[project]
icon = "https://media.discordapp.net/attachments/835619926667821117/1050055797100511292/image.png"
icon_width = "100px"
version = "1.0.0"

[variables]
information = ["Repository for the Advent Of Code challenges 🧩", "The directory structure is built like this: `src/<year>/<challenge day>/<part>.ts`, use this if you ever want to look for a solution 😄."]
installation = ["If you want to contribute or use this repository for your own **Advent Of Code** make sure you have the following: `yarn` and `node >= 18.16.0`."]