name: "ci: general tests"

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  Dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install Dependencies
        run: yarn install --immutable

  Building:
    runs-on: ubuntu-latest
    needs: Dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Run Compiler
        run: yarn run build
  Linting:
    runs-on: ubuntu-latest
    needs: Dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Run Eslint
        run: yarn run lint
#   Testing:
#     runs-on: ubuntu-latest
#     needs: Dependencies
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Install Node v18
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18
#           cache: yarn

#       - name: Install Dependencies
#         run: yarn install --immutable

#       - name: Run Vitest
#         run: yarn run test
