name: "ci: general tests"

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3

      - name: Install Node v16
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version: 16
          cache: yarn

      - name: Install Dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint

      - name: Run Compiler
        run: yarn build
